//
// Created by pszczypi on 08.12.2023.
//

#ifndef META_HEURISTIC_ALGORITHMS_NEIGHBOURHOODTYPE_H
#define META_HEURISTIC_ALGORITHMS_NEIGHBOURHOODTYPE_H
enum class NeighbourType {
    Swap,
    Insert,
    Invert,
};

#endif //META_HEURISTIC_ALGORITHMS_NEIGHBOURHOODTYPE_H
