//
// Created by Piotr Szczypior on 07/12/2023.
//

#ifndef META_HEURISTIC_ALGORITHMS_NEIGHBOURSERVICEFACTORY_H
#define META_HEURISTIC_ALGORITHMS_NEIGHBOURSERVICEFACTORY_H

#endif //META_HEURISTIC_ALGORITHMS_NEIGHBOURSERVICEFACTORY_H
