

#ifndef META_HEURISTIC_ALGORITHMS_SIMULATEDANNEALING_H
#define META_HEURISTIC_ALGORITHMS_SIMULATEDANNEALING_H


class SimulatedAnnealing {

};


#endif //META_HEURISTIC_ALGORITHMS_SIMULATEDANNEALING_H
