//
// Created by Zosia on 11.12.2023.
//

#ifndef META_HEURISTIC_ALGORITHMS_COOLINGDIAGRAMTYPE_H
#define META_HEURISTIC_ALGORITHMS_COOLINGDIAGRAMTYPE_H

enum class CoolingDiagramType {
    EXPONENTIAL,
    LINEAR,
    GEOMETRIC,
};


#endif //META_HEURISTIC_ALGORITHMS_COOLINGDIAGRAMTYPE_H
